### ISSUE TITLE
[1.12.2] Crashes upon startup if Entity Culling is installed.

### ISSUE THREAD

**Issue by SonicX8000** [Meldexun/RenderLib#1]
Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods:  5
[___MixinCompat-0.8___]
_MixinBootstrap-1.1.0
EntityCulling-1.12.2-5.3.3
Nothirium-1.12.2-0.1.0-beta
RenderLib-1.12.2-1.0.5

Crash:
[crash-2022-05-22_03.46.41-client.txt](https://github.com/Meldexun/RenderLib/files/8749092/crash-2022-05-22_03.46.41-client.txt)

Log:
[latest.log](https://github.com/Meldexun/RenderLib/files/8749094/latest.log)

Debug:
[debug.log](https://github.com/Meldexun/RenderLib/files/8749095/debug.log)

-----

Tried adding RenderLib + Nothirium to check out the performance, and the game crashes upon startup. If Entity Culling isn't installed, then the game boots up normally.

Unsure if the issue goes here, but the crash report mentions something with the Render, so I thought it would go here. Apologizes if this is the wrong place.

**Comment by Meldexun** [comment]
Earlier versions of EntityCulling are incompatible with this mod. EntityCulling-1.12.2-6.0.1-beta has RenderLib as a required dependency.
But I since curseforge needs some time to approve new mods, I couldn't just release the new EntityCulling version because RenderLib wasn't approved yet.

So you just need EntityCulling-6.0.1-beta or newer.

**Comment by SonicX8000** [comment]
Ah, alright. Wasn't aware that a new version was needed. I see the required jar on curseforge now as before I didn't see it.
