### ISSUE TITLE
I don't even understand what is wrong anymore.

### ISSUE THREAD

**Issue by Mixodinoguy** [Meldexun/RenderLib#23]
The best way I could describe what's going on is that I have a big mod pack and no matter how hard I try I cannot figure out what keeps crashing, I believe it may be something that is happening here, but I am not even sure of that.

This is the exit code and I will also show the crash report
-1

[crash-2023-02-28_22.16.44-client.txt](https://github.com/Meldexun/RenderLib/files/10856880/crash-2023-02-28_22.16.44-client.txt)
Sorry if this isn't a good bug report this is my first time doing it. I am usually able to just muddle my way around and find a solution but that is simply working this time.

**Comment by Meldexun** [comment]
Your description is fine but please use the issue template next time.

You definitely need RenderLib 1.12.2-1.2.5 for the Nothirium version that you have installed.
If the game is still crashing then you have to figure out the least amount of mods required to reporduce the crash otherwise I'm unable to investigate this further.

**Comment by MagmaSlime123** [comment]
Essential seems to be the cause.

**Comment by Mixodinoguy** [comment]
Thanks guys
