### ISSUE TITLE
No texture rendering with Intel graphics card

### ISSUE THREAD

**Issue by xJon** [Meldexun/RenderLib#44]
**Describe the bug**
> Most of the textures in the game are blank (just white/green blocks).

(https://github.com/xJon/The-1.12.2-Pack/issues/968)

**Versions**
RenderLib: https://mclo.gs/Rlu37bl#L82
Forge, Minecraft: https://mclo.gs/Rlu37bl#L4

**Hardware**
CPU: https://mclo.gs/Rlu37bl#L902
RAM: https://mclo.gs/Rlu37bl#L793
GPU: https://mclo.gs/Rlu37bl#L790

**Log File**
https://mclo.gs/Rlu37bl

Is there some workaround or config toggle that can be recommended, beyond removing RenderLib + Entity Culling? Thank you!

**Comment by Meldexun** [comment]
Why do you think that this is a RenderLib or EntityCulling issue?

**Comment by xJon** [comment]
I assumed so due to the repeated `[renderlib]: OpenGL API Error High 1281 GL error GL_INVALID_VALUE` errors in the log, but you are right that it's only an assumption. I will report back if removing them actually resolves the issue.

**Comment by Meldexun** [comment]
The config option in RenderLib enables the opengl debugging which is not limited to my code. Every opengl error will be logged properly this way (With properly I mean that the stacktrace is logged which tells you what code caused the error).
In this case I can see in the log that the Minecraft class (https://mclo.gs/Rlu37bl#L8695) and the TextureUtil class (https://mclo.gs/Rlu37bl#L8688) are modified. I suspect the mod that is responsible for these changes to one of these (or both) classes is the issue. (The mixin classes are named `MinecraftMixin` and `TextureUtilMixin` but I always name my mixins "Mixin*ClassName*". So, assuming these mixins are the issue then my mods can't be the cause.)

Edit: The source files of the other classes in the stack trace show no sign of mixins which is just wrong. Also, the minecraft class definitely has more than one mixin that modifies it. So, the source files that get reported in the stack trace are not accurate. This means the issue might **not** be caused by the mod that has the `MinecraftMixin` and/or `TextureUtilMixin`. But it's still likely caused by some mod that modifies the code from the stack trace. (I don't touch texture mapping, ticking, or whatever which means this likely isn't caused by one of my mods)

**Comment by xJon** [comment]
Thank you for the tip, my bad. In this case I'll close this.
